accounts/urls.py
# from django.conf.urls import url
# from .import views

# app_name = 'accounts'

# urlpatterns = [
#     url(r'^signup/$', views.signup_view, name='signup'),
#     url(r'^login/$', views.login_view, name='login'),
#     url(r'^logout/$', views.logout_view, name='logout')

# ]

from django.urls import path
from .import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout')
]

blogpost/urls.py
# from django.conf.urls import url, include
# from django.contrib import admin
# from . import views
# from django.contrib.staticfiles.urls import staticfiles_urlpatterns
# from django.conf.urls.static import static
# from django.conf import settings
# # from posts import views as post_views

# urlpatterns = [
#     url(r'^admin/', admin.site.urls),
#     url(r'^about/$', views.about),
#     # url(r'^$',post_views.posts, name="home"),
#     url(r'^accounts/',include('accounts.urls')),
#     url(r'^posts/',include('posts.urls')),
# ]

# urlpatterns +=staticfiles_urlpatterns()
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


from django.urls import path, include
from django.contrib import admin
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/', views.about),
    # path('', post_views.posts, name="home"),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

 

posts/urls.py
# from django.conf.urls import url
# from . import views

# app_name = 'posts'

# urlpatterns = [
#     url(r'^$',views.posts, name='list'),
#     url(r'^create/$',views.post_create, name='create'),
#     url(r"^(?P<slug>[\w-]+)/$", views.post_detail, name='detail'),
# ]



from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.posts, name='list'),
    path('create/', views.post_create, name='create'),
    path('<slug:slug>/', views.post_detail, name='detail'),
]

accounts/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

posts/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png', blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50] + "..."

class Comment(models.Model):
    post = models.ForeignKey('posts.Post', on_delete=models.CASCADE, related_name='comments')
    author = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.text
        

posts/forms.py
from django import forms
from . import models
# from .models import Post, Comment

class CreatePost(forms.ModelForm):
    class Meta:
        model = models.Post
        fields = ['title','body','slug']

class CommentForm(forms.ModelForm):
    class Meta:
        model = models.Comment
        fields = ('author', 'text',)

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, authenticate, logout

# Create your views here.
def signup_view(request):
    # form = UserCreationForm()
    # if request.method == 'POST':
    #     form = UserCreationForm(request.POST)
    #     if form.is_valid():
    #         user=form.save()
    #         return redirect('posts:list')
    # else:
    #     form = UserCreationForm()
    # return render(request, 'accounts/signup.html',{'form': form })
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('posts:list')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form': form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid(): 
            # log in the user
            user = form.get_user()
            login(request,user)
            return redirect('posts:list')   
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html',{'form': form })

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('posts:list')   

blogpost/views.py
from django.http import HttpResponse
from django.shortcuts import render

def homepage(request):
    # return HttpResponse('This is the homepage')
    return render(request,'homepage.html')

def about(request):
    # return HttpResponse('We like Django')
    return render(request,'about.html')

posts/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render, redirect
from .models import Post
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import forms
# Create your views here.
def posts(request):
    posts = Post.objects.all().order_by('date')
    return render(request, 'posts/blogposts.html', {'posts': posts})

def post_detail(request,slug):
    # return HttpResponse(slug)

    post= Post.objects.get(slug=slug)
    return render(request, 'posts/post_detail.html', {'post':post})

@login_required(login_url="/accounts/login/")
def post_create(request):
    if request.method == 'POST':
        form = forms.CreatePost(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            #save form to db
            return redirect("posts:list")
    else:
        form = forms.CreatePost()
    return render(request, 'posts/post_create.html',{'form':form})

accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}
{% block content %}
<h1>Login</h1>
<form action="/accounts/login/" class="site-form" method="post">
    {%csrf_token%}
    {{ form }}
    <input type="submit" value="Login">
</form>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}
<h1>Signup</h1>
<form action="/accounts/signup/" class="site-form" method="post">
    {%csrf_token%}
    
    {{ form }}
    <input type="submit" value="Signup">
</form>

{% endblock %}

posts/templates/posts/blogposts.html
{% extends 'base_layout.html' %}

{% block content %}
<h1>Blog Posts</h1>
{%for post in posts%}
<div class="posts">
    <div class="post">
        <div class="date">
            {{ post.date }}
        </div>
        <h2><a href="{% url 'posts:detail' slug=post.slug %}">{{ post.title }}</a></h2>
        <p>{{ post.snippet }}</p>
        <a href="{% url 'posts:detail' slug=post.slug %}">Comments: {{ post.comments.count }}</a>
    </div>
{% endfor %}
</div>
{% endblock %}

posts/templates/posts/post_create.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="create_post">
    <h2>Create a New post</h2>
    <form action="/posts/create/" class="site-form" method="post">
        {%csrf_token%}
        {{ form }}
        <input type="submit" value="Create">
    </form>

</div>
{% endblock %}

posts/templates/posts/post_detail.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="post-detail">
    <div class="post">
        <h2>{{post.title}}</h2>
        <img src="{{post.thumb.url}}" alt="">
        <p>{{post.body}}</p>
        <p>{{post.date}}</p>
    </div>
</div>

<hr>
{% for comment in post.comments.all %}
    <div class="comment">
        <div class="date">{{ comment.created_date }}</div>
        <strong>{{ comment.author }}</strong>
        <p>{{ comment.text|linebreaks }}</p>
    </div>
{% empty %}
    <p>No comments here yet :(</p>
{% endfor %}

{% endblock %}

templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>About</title>
</head>
<body>
    <h1>About Us</h1>
    <p>We like Django</p>
</body>
</html>

templates/base_layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>POSTS</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>

<body>
    <div class="wrapper">
        <nav>
           <ul>
               {% if user.is_authenticated%}
               <li>
                   <form action="{% url 'accounts:logout'%}" class="logout-link" method="post">
                       {%csrf_token%}
                       <button type="submit">Logout</button>
                   </form>
               </li>
               <li><a href="/posts/create" class="highlight">Post A Question</a></li>
               {% else %}
               <li><a href="/accounts/login">Login</a></li>
               <li><a href="/accounts/signup">Signup</a></li>
               {% endif %}
           </ul>
        </nav>
        {% block content %}

        {% endblock %}
    </div> 
</body>
</html>

templates/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Homepage</title>
</head>
<body>
    <h1>This is the Homepage</h1>
    <p>Welcome to  Ernest's blog posts</p>
</body>
</html>